modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "dt_expandedecosphere"
version = "${file.jarVersion}"
displayName = "Dynamic Trees for William Wythers' E Overworld"

updateJSONURL = "https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/Quark.json?raw=true"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark"
credits="Max Hyper"
authors="Docvin"
description='''
Compatibility Mod between Dynamic trees and William Wythers' Expanded Ecosphere
'''

[[dependencies.dt_expandedecosphere]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dt_expandedecosphere]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dt_expandedecosphere]]
    modId = "dynamictrees"
    mandatory = true
    versionRange = "[1.3.0-BETA6,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.dt_expandedecosphere]]
    modId = "dynamictreesplus"
    mandatory = false
    versionRange = "[1.2.0-BETA1,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.dt_expandedecosphere]]
    modId = "expanded_ecosphere"
    mandatory = true
    versionRange = "[3.2.4,)"
    ordering = "AFTER"
    side = "BOTH"